version: 0.0.{build}

pull_requests:
  do_not_increment_build_number: true

os: Visual Studio 2017

platform:
  - x86

branches:
  only:
    - master

environment:
  matrix:
    - flavor: mingw
      QTDIR: C:\Qt\5.9\mingw53_32

    - flavor: msvc
      QTDIR: C:\Qt\5.9\msvc2017_64

init:
  - if %flavor%==mingw set PATH=C:\Qt\Tools\mingw530_32\bin;%PATH%
  - set PATH=%QTDIR%\bin;%PATH%
  - set PEGASUS_HOME=C:\hello\world

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - git submodule update --init

build_script:
  - md build
  - cd build
  - qmake ..
  - if %flavor%==msvc (nmake /NOLOGO) else (mingw32-make)
  - if %flavor%==msvc (nmake /NOLOGO check) else (mingw32-make check)
  - if %flavor%==msvc (nmake /NOLOGO install) else (mingw32-make install)

  - windeployqt
      --release
      --plugindir C:\pegasus-frontend\lib
      --qmldir ..
      --no-translations
      --no-opengl-sw
      C:\pegasus-frontend
  - md C:\pegasus-frontend\lib\qml
  - ps: Get-ChildItem C:\pegasus-frontend -Filter 'Qt*' -Directory |
      Move-Item -Destination C:\pegasus-frontend\lib\qml

  - copy ..\README.md C:\pegasus-frontend
  - copy ..\LICENSE.md C:\pegasus-frontend
  - 7z a pegasus_ci.zip C:\pegasus-frontend
  - git describe --always > tmp_out.txt
  - set /p SUFFIX=<tmp_out.txt
  - cp pegasus_ci.zip ../pegasus-fe_%SUFFIX%_win-%flavor%.zip

artifacts:
  - path: build\pegasus_ci.zip
  - path: pegasus-fe_*.zip

deploy:
  - provider: GitHub
    tag: continuous
    auth_token:
      secure: CVaZqFcPrvYAVCGTNv1SRln6j+IAvv+J0Gaz0vUD3fsHMYm7Zuf+NivLxgWNkwNe
    artifact: /pegasus-fe_.*\.zip/
    prerelease: true
    on:
      branch: master
      flavor: mingw
      appveyor_repo_tag: true
