language: cpp

sudo: required
dist: trusty

branches:
  only:
  - master

env:
  global:
  - TOOLS_URL=https://github.com/mmatyas/pegasus-frontend/releases/download/alpha1
  - QT_VER=qt592
  - PEGASUS_HOME=/hello/world
  matrix:
  - TARGET=x11-static
  - TARGET=rpi1-static CROSS=1
  - TARGET=rpi2-static CROSS=1

git:
  depth: 100

before_install:
  - pushd /tmp
  - wget ${TOOLS_URL}/${QT_VER}_${TARGET}.tgz
  - if [[ -n "$CROSS" ]]; then wget ${TOOLS_URL}/rpi-toolchain.tgz; fi
  - if [[ -n "$CROSS" ]]; then wget ${TOOLS_URL}/rpi-sysroot.tgz; fi
  - for f in *.tgz; do sudo tar xzf ${f} -C /; done
  - if [[ -n "$CROSS" ]]; then sudo mv /rpi-sysroot /opt/; fi
  - if [[ "$TARGET" == "x11-static" ]]; then
      sudo ln -s ${QT_VER}_${TARGET} /opt/${QT_VER}_${TARGET}_hosttools;
      sudo apt-get -qq update &&
      sudo apt-get install -y
        libasound-dev
        libgstreamer-plugins-base1.0-dev
        libpulse-dev
        libudev-dev
        libxi-dev
      ;
    fi
  - sudo mkdir /opt/pegasus-frontend
  - sudo chown travis:travis /opt/pegasus-frontend
  - popd

before_script:
  - if [[ $TARGET == x11* ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

script:
  - if [[ $TARGET == x11* ]]; then
      find -name *.qml -exec /opt/${QT_VER}_${TARGET}/bin/qmllint {} \; ;
    fi
  - if [[ $TARGET == *static ]]; then
      ln -s ../frontend src/app/qml-frontend;
      ln -s ../themes/pegasus-grid src/app/qml-theme;
    fi
  - mkdir build && cd build
  - /opt/${QT_VER}_${TARGET}_hosttools/bin/qmake ..
  - make
  - if [[ $TARGET == x11* ]]; then make check; fi
  - make install

after_success:
  - export SUFFIX=$(git describe --always)_${TARGET}
  - zip -j pegasus-fe_${SUFFIX}.zip
      /opt/pegasus-frontend/pegasus-fe
      ../README.md
      ../LICENSE.md
  - curl --upload-file
      pegasus-fe_${SUFFIX}.zip
      https://transfer.sh/pegasus-fe_${SUFFIX}.zip
  - wget -c https://github.com/mmatyas/uploadtool/raw/master/upload.sh
  - bash ./upload.sh pegasus-fe_${SUFFIX}.zip

matrix:
  include:
    # OSX build
    - os: osx
      compiler: clang
      env: null
      before_install:
        - brew update
      install:
        - brew install qt5
        - brew link --force qt5
        - qmake -v
      script:
        - mkdir build && cd build
        - qmake ..
        - make check
      after_success:
        - true
    # Qt 5.7.1 (for Debian Stretch/Ubuntu Zesty)
    - env: QT_QPA_PLATFORM=minimal
      before_install:
        - sudo add-apt-repository -y ppa:beineri/opt-qt571-trusty
        - sudo apt-get update
      install:
        - sudo apt-get install -y
            qt57declarative
            qt57graphicaleffects
            qt57gamepad
            qt57imageformats
            qt57multimedia
            qt57svg
            qt57tools
        - source /opt/qt57/bin/qt57-env.sh
        - qmake -v
      script:
        - mkdir build && cd build
        - qmake ..
        - make check
      after_success:
        - true
