language: cpp

sudo: required
dist: trusty

branches:
  only:
  - master

env:
  global:
  - TOOLS_URL=https://github.com/mmatyas/pegasus-frontend/releases/download/alpha1
  matrix:
  - TARGET=x11-static
  - TARGET=rpi1-static CROSS=1
  - TARGET=rpi2-static CROSS=1

before_install:
  - pushd /tmp
  - wget ${TOOLS_URL}/qt59_${TARGET}.tgz
  - if [[ -n "$CROSS" ]]; then wget ${TOOLS_URL}/rpi-toolchain.tgz; fi
  - if [[ -n "$CROSS" ]]; then wget ${TOOLS_URL}/rpi-sysroot.tgz; fi
  - for f in *.tgz; do sudo tar xzf ${f} -C /; done
  - if [[ -n "$CROSS" ]]; then sudo mv /rpi-sysroot /opt/; fi
  - if [[ "$TARGET" == "x11-static" ]]; then
      sudo ln -s qt59_${TARGET} /opt/qt59_${TARGET}_hosttools;
      sudo apt-get -qq update &&
      sudo apt-get install -y
        libasound-dev
        libgstreamer-plugins-base1.0-dev
        libpulse-dev
        libsdl2-dev
        libudev-dev
        libxi-dev
      ;
    fi
  - sudo mkdir /opt/pegasus-frontend
  - sudo chown travis:travis /opt/pegasus-frontend
  - popd

script:
  - if [[ $TARGET == x11* ]]; then
      find -name *.qml -exec /opt/qt59_${TARGET}/bin/qmllint {} \; ;
    fi
  - if [[ $TARGET == *static ]]; then
      ln -s ../frontend src/app/qml-frontend;
      ln -s ../themes/pegasus-grid src/app/qml-theme;
    fi
  - /opt/qt59_${TARGET}_hosttools/bin/qmake
  - make
  - make install

after_success:
  - export SUFFIX=$(git describe --always --tags --dirty)_${TARGET}
  - zip pegasus-fe_${SUFFIX}.zip /opt/pegasus-frontend/*
  - curl --upload-file
      pegasus-fe_${SUFFIX}.zip
      https://transfer.sh/pegasus-ci_${TARGET}
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh pegasus-fe_${SUFFIX}.zip

matrix:
  include:
    - os: osx
      compiler: clang
      env: null
      before_install:
        - brew update
      install:
        - brew install qt5
        - brew link --force qt5
        - qmake -v
      script:
        - qmake
        - make
      after_success:
        - true
