language: cpp

sudo: required
dist: trusty
services:
  - docker

branches:
  only:
  - master

env:
  global:
  - TOOLS_URL=https://github.com/mmatyas/pegasus-frontend/releases/download/alpha1
  matrix:
  - TARGET=x11 CROSS=0
  - TARGET=rpi1 CROSS=1
  - TARGET=rpi2 CROSS=1

before_install:
  - pushd /tmp
  - mkdir deploy build tools
  - wget ${TOOLS_URL}/qt58-${TARGET}.tgz
  - if [[ "$CROSS" == "1" ]]; then wget ${TOOLS_URL}/rpi-toolchain.tgz; fi
  - if [[ "$CROSS" == "1" ]]; then wget ${TOOLS_URL}/rpi-sysroot.tgz; fi
  - for f in *.tgz; do tar xzf ${f} -C ./tools; done
  - if [[ "$CROSS" == "1" ]]; then mv ./tools/rpi-sysroot ./tools/opt/; fi
  - popd

install:
  - docker pull mmatyas/pegasus-ci
  - export DOCKER_CMD='docker run
      --volume /tmp/tools/opt:/opt:ro
      --volume '$PWD':/src:ro
      --volume /tmp/build:/build
      --volume /tmp/deploy:/deploy
      mmatyas/pegasus-ci'

script:
  - if [[ "$TARGET" == "x11" ]]; then
      ${DOCKER_CMD} /bin/bash -c '
        LD_LIBRARY_PATH=/opt/qt58-x11/lib/
        find /src -name *.qml -exec /opt/qt58-x11/bin/qmllint {} \;
      ';
    fi
  - ${DOCKER_CMD}
      /opt/qt58-${TARGET}_hosttools/bin/qmake
      INSTALLDIR=/deploy
      /src
  - ${DOCKER_CMD} make
  - ${DOCKER_CMD} make install
  - curl --upload-file /tmp/deploy/pegasus https://transfer.sh/pegasus-${TARGET}

matrix:
  include:
    - os: osx
      compiler: clang
      env: null
      before_install:
        - brew update
      install:
        - brew install qt5
        - brew link --force qt5
        - qmake -v
      script:
        - qmake
        - make
