language: cpp

sudo: required

env:
  global:
    - QT_VER=5.12.3


install: .travis/install.sh
script: .travis/script.sh

jobs:
  include:
  - env: TARGET=x11-static
    dist: xenial
  - env: TARGET=macos-static
    os: osx

services:
  - xvfb
