version: 2
jobs:
  android:
    docker:
      - image: mmatyas/pegasus-qt-android
    environment:
      - QT_VERSION: qt5123
      - QT_TARGET: android
      - ANDROID_NDK_ROOT: /opt/android-ndk
    steps:
      - checkout
      - run: .circleci/prepare.sh
      - run: .circleci/build.sh
      - run: curl -LO https://github.com/mmatyas/pegasus-frontend/releases/download/alpha1/aks.enc
      - run: openssl aes-256-cbc -k "${AKS_ENC_KEY}" -in aks.enc -out aks -d
      - run: /opt/${QT_VERSION}_${QT_TARGET}/bin/androiddeployqt
          --input src/app/android-libpegasus-fe.so-deployment-settings.json
          --output ${PWD}/installdir
          --android-platform android-22
          --gradle
          --sign ./aks "${AKS_ALIAS}"
          --storepass "${AKS_STOREPASS}"
          --keypass "${AKS_KEYPASS}"
      # Deploy
      - run: cp
          installdir/build/outputs/apk/release/installdir-release-signed.apk
          dist/pegasus-fe_$(git describe --always)_android.apk
      - run: .circleci/release.sh
  mingw:
    docker:
      - image: mmatyas/pegasus-qt-mingw
    environment:
      - QT_VERSION: qt5123
      - QT_TARGET: win32-mingw-static
    steps:
      - checkout
      - run: .circleci/prepare.sh
      - run: .circleci/build.sh
      - run: i686-w64-mingw32-objdump -p installdir/home/build/project/src/app/C:/pegasus-frontend/pegasus-fe.exe | grep 'DLL Name' | sort
      # Deploy
      - run: zip -j dist/pegasus-fe_$(git describe --always)_win-mingw-static.zip
          installdir/home/build/project/src/app/C:/pegasus-frontend/pegasus-fe.exe
          README.md
          LICENSE.md
      - run: .circleci/release.sh
  buster-pi4:
    docker:
      - image: mmatyas/pegasus-qt-buster
    environment:
      - QT_VERSION: qt5124
      - QT_TARGET: rpi4-static
    steps:
      - checkout
      - run: .circleci/prepare.sh
      - run: .circleci/build.sh
      - run: arm-linux-gnueabihf-objdump -p installdir/opt/pegasus-frontend/pegasus-fe | grep 'NEEDED' | sort
      # Deploy
      - run: zip -j dist/pegasus-fe_$(git describe --always)_rpi4-static.zip
          installdir/opt/pegasus-frontend/pegasus-fe
          README.md
          LICENSE.md
      - run: .circleci/release.sh
workflows:
  version: 2
  all:
    jobs:
      - android
      - mingw
      - buster-pi4
